[package]
name = "segment_tree"
version = "0.1.0"
authors = ["Amos Onn <amosonn@gmail.com>"]
description = "Segment-tree and Segment-array-tree data structures"
edition = "2018"

[dependencies]
thiserror = "1.0.19"

[dev-dependencies]
assert_let = { path = "../assert_let"}
